export const innerRoutePath = {
  getMain: () => '/',
  getDocs: () => '/docs',
  getPricing: () => '/pricing',
  getVerification: () => '/verification',
  getStartPage: () => '/start-journey',
  getDashboard: () => '/dashboard',
  getTransactionHistory: () => '/transactions',
  getActivity: () => '/activity',
  getTransactions: () => '/transactions',
  getDeposit: () => '/deposit',
  getExplore: () => '/explore',
  getRewards: () => '/rewards',
  getAdditionalInfo: () => '/additional-info',
  getProfileSettings: () => '/profile-settings',
  getForgetPassword: () => '/forget-password',
  getPasswordReset: (hash: string) => `/password-reset/${hash}`,
  getSignUp: (queryString: string = '') => `/sign-up${queryString}`,
  getAll: () => '*',
};
